#!/usr/bin/env python3
"""Minimal localhost-only ComfyUI API client using Python stdlib."""

from __future__ import annotations

import argparse
import http.client
import json
import os
import pathlib
import time
import urllib.parse

_ALLOWED_ENDPOINTS = {
    "http://127.0.0.1:8188",
    "http://localhost:8188",
}
_CONFIGURED_URL = os.environ.get("NEXLABS_COMFY_URL", "http://127.0.0.1:8188").rstrip("/")

if _CONFIGURED_URL not in _ALLOWED_ENDPOINTS:
    raise SystemExit(
        "NEXLABS_COMFY_URL must be a localhost-only ComfyUI endpoint on port 8188."
    )

# Connect to the numeric loopback address even when the accepted configuration
# uses the localhost alias. This keeps the transport pinned to the local host.
_HOST = "127.0.0.1"
_PORT = 8188


def request(path: str, data: dict | None = None, timeout: int = 15):
    if not path.startswith("/") or "://" in path:
        raise ValueError("ComfyUI API path must be a local absolute path.")

    body = None
    headers = {}
    method = "GET"

    if data is not None:
        body = json.dumps(data).encode("utf-8")
        headers["Content-Type"] = "application/json"
        method = "POST"

    conn = http.client.HTTPConnection(_HOST, _PORT, timeout=timeout)
    try:
        conn.request(method, path, body=body, headers=headers)
        response = conn.getresponse()
        raw = response.read()

        if response.status < 200 or response.status >= 300:
            raise RuntimeError(
                f"ComfyUI returned HTTP {response.status} for {path}: "
                f"{raw[:500].decode('utf-8', errors='replace')}"
            )

        content_type = response.getheader("Content-Type", "")
        if "json" in content_type:
            return json.loads(raw.decode("utf-8"))
        return raw
    finally:
        conn.close()


def health() -> int:
    try:
        request("/")
        print(
            json.dumps(
                {
                    "status": "PASS",
                    "url": _CONFIGURED_URL,
                    "transport": f"http://{_HOST}:{_PORT}",
                    "localhost_only": True,
                }
            )
        )
        return 0
    except Exception as exc:
        print(
            json.dumps(
                {
                    "status": "FAIL",
                    "url": _CONFIGURED_URL,
                    "localhost_only": True,
                    "error": str(exc),
                }
            )
        )
        return 1


def queue(workflow_path: str, timeout: int) -> int:
    workflow_file = pathlib.Path(workflow_path).resolve(strict=True)
    if not workflow_file.is_file():
        raise SystemExit(f"Workflow is not a file: {workflow_file}")

    workflow = json.loads(workflow_file.read_text(encoding="utf-8"))
    result = request("/prompt", {"prompt": workflow})
    prompt_id = result.get("prompt_id")

    if not prompt_id or not isinstance(prompt_id, str):
        print(json.dumps({"status": "FAIL", "response": result}, indent=2))
        return 2

    # Prompt IDs are generated by the local ComfyUI server. Encode them before
    # using them as a path segment.
    encoded_prompt_id = urllib.parse.quote(prompt_id, safe="")
    deadline = time.time() + timeout

    while time.time() < deadline:
        history = request(f"/history/{encoded_prompt_id}")
        if prompt_id in history:
            print(
                json.dumps(
                    {
                        "status": "PASS",
                        "prompt_id": prompt_id,
                        "history": history[prompt_id],
                    },
                    indent=2,
                )
            )
            return 0
        time.sleep(1.0)

    print(json.dumps({"status": "TIMEOUT", "prompt_id": prompt_id}))
    return 3


def main() -> int:
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="cmd", required=True)
    sub.add_parser("health")

    queue_parser = sub.add_parser("queue")
    queue_parser.add_argument("workflow")
    queue_parser.add_argument("--timeout", type=int, default=900)

    args = parser.parse_args()
    if args.cmd == "health":
        return health()
    return queue(args.workflow, args.timeout)


if __name__ == "__main__":
    raise SystemExit(main())
